workflows:
  build-android-apk:
    name: Build Android APK
    max_build_duration: 60
    environment:
      flutter: stable   # آخر نسخة Flutter stable
    working_directory: live_audio_room
    scripts:
      - name: Get dependencies
        script: flutter pub get
      - name: Build APK (Release)
        script: flutter build apk --release
    artifacts:
      - live_audio_room/build/app/outputs/flutter-apk/app-release.apk
    publishing:
      email:
        recipients:
          - your-email@example.com
